[phases.setup]
nixPkgs = ["python3", "cairo", "pango", "gdk-pixbuf", "glib", "pkg-config", "gobject-introspection"]

[phases.install]
dependsOn = ["setup"]
cmds = ["pip install -r requirements.txt"]
