[phases.setup]
# On ajoute xhtml2pdf ici. Nix va installer la version binaire pré-compilée.
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.xhtml2pdf", "cairo", "pkg-config", "gobject-introspection", "gcc"]

[phases.install]
# On installe le reste (discord, openai) via pip sans toucher aux paquets système
cmds = ["pip install -r requirements.txt --break-system-packages"]

[start]
cmd = "python3 bot.py"
